# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.0.1'
gem 'activesupport'
gem 'bcrypt'
gem 'dry-system', '0.18.1'
gem 'dry-validation'
gem 'erubis', '~> 2.7.0'
gem 'i18n'
gem 'oj'
gem 'pry'
gem 'puma', '~> 5.2'
gem 'rake'
gem 'roda', '~> 3.41'
gem 'roda-enhanced_logger'
gem 'sequel', '5.44'
gem 'sequel_pg', '>= 1.14'
gem 'sequel_secure_password'
gem 'tilt', '~> 2.0.1'
gem 'timecop'
gem 'yard'

group :development, :test do
  gem 'dotenv'
  gem 'factory_bot'
  gem 'rack-test'
  gem 'rspec'
  gem 'rubocop'
  gem 'rubocop-performance'
  gem 'rubocop-rake'
  gem 'rubocop-rspec'
  gem 'rubocop-sequel'
  gem 'rubocop-thread_safety'
end

# gem 'wdm', '>= 0.1.0' if Gem.win_platform?
# gem 'sqlite3'
# gem 'pg', '0.18.1'
# gem 'bigdecimal', '1.3.5'
