# frozen_string_literal: true

source "https://rubygems.org"

gem "puma"
gem "roda", "~> 2.1.0"
gem "tilt", "~> 2.0.1"
gem "erubis", "~> 2.7.0"
# gem 'wdm', '>= 0.1.0' if Gem.win_platform?
# gem 'sqlite3'
gem "pg", "~> 0.18.1"
gem "sequel", "~> 4.21.0"
# gem 'sequel_pg', :require=>'sequel'
# gem 'bigdecimal', '1.3.5'

